<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260516025430 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_page_content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, image VARCHAR(255) NOT NULL, image_alt VARCHAR(255) NOT NULL, inline_price_amount VARCHAR(20) DEFAULT NULL, inline_price_description VARCHAR(100) DEFAULT NULL, features JSON NOT NULL, price_cards JSON NOT NULL, pricing_eyebrow VARCHAR(100) DEFAULT NULL, pricing_title VARCHAR(150) DEFAULT NULL, pricing_lead TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D1D197D989D9B62 ON activity_page_content (slug)');
        $this->addSql('CREATE TABLE admin_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD8A54A9E7927C74 ON admin_user (email)');
        $this->addSql('CREATE TABLE anniv_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(50) NOT NULL, icon VARCHAR(10) NOT NULL, name VARCHAR(100) NOT NULL, age VARCHAR(50) NOT NULL, price VARCHAR(50) NOT NULL, features JSON NOT NULL, featured BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C22917B88A90ABA9 ON anniv_card (key)');
        $this->addSql('CREATE TABLE day_schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(20) NOT NULL, label VARCHAR(20) NOT NULL, hours VARCHAR(50) NOT NULL, js_day SMALLINT NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_597636878A90ABA9 ON day_schedule (key)');
        $this->addSql('CREATE TABLE hebdo_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(50) NOT NULL, tag VARCHAR(100) NOT NULL, title VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, bullets JSON NOT NULL, price VARCHAR(50) NOT NULL, days VARCHAR(100) NOT NULL, featured BOOLEAN NOT NULL, savings VARCHAR(100) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AEC885738A90ABA9 ON hebdo_card (key)');
        $this->addSql('CREATE TABLE menu_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(50) NOT NULL, title VARCHAR(150) NOT NULL, position INT NOT NULL, section_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2A1D5C57D823E37A ON menu_category (section_id)');
        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, description VARCHAR(300) NOT NULL, price VARCHAR(50) NOT NULL, position INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D754D55012469DE2 ON menu_item (category_id)');
        $this->addSql('CREATE TABLE menu_section (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(50) NOT NULL, eyebrow VARCHAR(150) NOT NULL, title VARCHAR(150) NOT NULL, title_accent VARCHAR(150) NOT NULL, lead TEXT DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A5A867518A90ABA9 ON menu_section (key)');
        $this->addSql('CREATE TABLE offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(50) NOT NULL, image VARCHAR(255) NOT NULL, title VARCHAR(150) NOT NULL, badge VARCHAR(50) NOT NULL, badge_variant VARCHAR(20) NOT NULL, href VARCHAR(200) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29D6873E8A90ABA9 ON offer (key)');
        $this->addSql('CREATE TABLE pass_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, price VARCHAR(50) NOT NULL, features JSON NOT NULL, separate_price VARCHAR(50) NOT NULL, savings VARCHAR(50) NOT NULL, featured BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7CEDD528A90ABA9 ON pass_card (key)');
        $this->addSql('CREATE TABLE resa_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(50) NOT NULL, rank VARCHAR(20) NOT NULL, audience VARCHAR(100) NOT NULL, price VARCHAR(50) NOT NULL, pitch VARCHAR(200) NOT NULL, features JSON NOT NULL, key_point TEXT NOT NULL, featured BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_336C58BE8A90ABA9 ON resa_card (key)');
        $this->addSql('CREATE TABLE tarif_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, card_group VARCHAR(20) NOT NULL, icon VARCHAR(10) NOT NULL, name VARCHAR(100) NOT NULL, unit VARCHAR(150) NOT NULL, note VARCHAR(500) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tarif_price_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(150) NOT NULL, price VARCHAR(50) NOT NULL, position INT NOT NULL, tarif_card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FDAB43AE39ADE865 ON tarif_price_line (tarif_card_id)');
        $this->addSql('CREATE TABLE vip_feature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, icon VARCHAR(10) NOT NULL, label VARCHAR(100) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE menu_category ADD CONSTRAINT FK_2A1D5C57D823E37A FOREIGN KEY (section_id) REFERENCES menu_section (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D55012469DE2 FOREIGN KEY (category_id) REFERENCES menu_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarif_price_line ADD CONSTRAINT FK_FDAB43AE39ADE865 FOREIGN KEY (tarif_card_id) REFERENCES tarif_card (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE menu_category DROP CONSTRAINT FK_2A1D5C57D823E37A');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D55012469DE2');
        $this->addSql('ALTER TABLE tarif_price_line DROP CONSTRAINT FK_FDAB43AE39ADE865');
        $this->addSql('DROP TABLE activity_page_content');
        $this->addSql('DROP TABLE admin_user');
        $this->addSql('DROP TABLE anniv_card');
        $this->addSql('DROP TABLE day_schedule');
        $this->addSql('DROP TABLE hebdo_card');
        $this->addSql('DROP TABLE menu_category');
        $this->addSql('DROP TABLE menu_item');
        $this->addSql('DROP TABLE menu_section');
        $this->addSql('DROP TABLE offer');
        $this->addSql('DROP TABLE pass_card');
        $this->addSql('DROP TABLE resa_card');
        $this->addSql('DROP TABLE tarif_card');
        $this->addSql('DROP TABLE tarif_price_line');
        $this->addSql('DROP TABLE vip_feature');
    }
}
