<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260518201638 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE demande_reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(12) NOT NULL, status VARCHAR(20) NOT NULL, formule_key VARCHAR(50) NOT NULL, event_date DATE NOT NULL, time_slot VARCHAR(5) NOT NULL, child_name VARCHAR(80) NOT NULL, child_age SMALLINT NOT NULL, kids_count SMALLINT NOT NULL, cake_note VARCHAR(300) DEFAULT NULL, allergies VARCHAR(300) DEFAULT NULL, parent_first_name VARCHAR(80) NOT NULL, parent_last_name VARCHAR(80) NOT NULL, parent_email VARCHAR(180) NOT NULL, parent_phone VARCHAR(20) NOT NULL, source VARCHAR(20) DEFAULT NULL, message VARCHAR(1000) DEFAULT NULL, accept_cgv BOOLEAN NOT NULL, accept_newsletter BOOLEAN NOT NULL, upsell_vr BOOLEAN NOT NULL, unit_price_cents_snapshot INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E3EF1621AEA34913 ON demande_reservation (reference)');
        $this->addSql('CREATE INDEX idx_event_slot ON demande_reservation (event_date, time_slot)');
        $this->addSql('ALTER TABLE anniv_card ADD unit_price_cents INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE anniv_card ADD min_kids INT DEFAULT 6 NOT NULL');
        $this->addSql('ALTER TABLE anniv_card ADD duration VARCHAR(20) DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE anniv_card ADD tagline VARCHAR(200) DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER INDEX uniq_app_user_email RENAME TO UNIQ_88BDF3E9E7927C74');
        $this->addSql('ALTER TABLE offer ALTER active DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE demande_reservation');
        $this->addSql('ALTER TABLE anniv_card DROP unit_price_cents');
        $this->addSql('ALTER TABLE anniv_card DROP min_kids');
        $this->addSql('ALTER TABLE anniv_card DROP duration');
        $this->addSql('ALTER TABLE anniv_card DROP tagline');
        $this->addSql('ALTER INDEX uniq_88bdf3e9e7927c74 RENAME TO uniq_app_user_email');
        $this->addSql('ALTER TABLE offer ALTER active SET DEFAULT true');
    }
}
