<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260518222859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE b2b_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(16) NOT NULL, stage VARCHAR(20) NOT NULL, type VARCHAR(30) NOT NULL, company_name VARCHAR(120) NOT NULL, contact_first_name VARCHAR(80) NOT NULL, contact_last_name VARCHAR(80) NOT NULL, contact_email VARCHAR(180) NOT NULL, contact_phone VARCHAR(20) NOT NULL, event_date DATE DEFAULT NULL, expected_attendees SMALLINT NOT NULL, message TEXT DEFAULT NULL, estimated_value_cents INT DEFAULT NULL, admin_note TEXT DEFAULT NULL, accept_rgpd BOOLEAN NOT NULL, internal_qualified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, internal_quoted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, internal_negotiated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, internal_closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5751D4B9AEA34913 ON b2b_request (reference)');
        $this->addSql('CREATE INDEX idx_b2b_stage_created ON b2b_request (stage, created_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE b2b_request');
    }
}
